# Generated by Django 4.2.30 on 2026-06-12 13:05

import bookings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[bookings.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(validators=[bookings.validators.validate_booking_date]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(validators=[bookings.validators.validate_booking_time]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, validators=[bookings.validators.validate_no_sql_injection]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('installation', 'Installation')], max_length=20, validators=[bookings.validators.validate_service_type]),
        ),
    ]
